name: Deploy FastAPI App to AWS Lambda

on:
  workflow_dispatch:  # This triggers the workflow manually


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          pip install --use-feature=in-tree-build .

      - name: Create ZIP file
        run: |
          zip -r lambda_function.zip ./

      - name: Upload ZIP file to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-central-1
        # Replace secrets.AWS_S3_BUCKET, secrets.AWS_ACCESS_KEY_ID, and secrets.AWS_SECRET_ACCESS_KEY with your own secrets
